name: store_app_clean_architecture
description: A new Flutter project.
publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  smooth_page_indicator: ^1.1.0
  equatable: ^2.0.5
  dio: ^5.3.0
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  dartz: ^0.10.1
  get_it: ^7.6.0
  cached_network_image: ^3.2.3
  loading_animation_widget: ^1.2.0+4
  dotted_dashed_line: ^0.0.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  zarinpal: ^1.0.5
  url_launcher: ^6.1.12
  uni_links: ^0.5.1
  intl: ^0.18.1
  # flutter_secure_storage: ^8.0.0 #this work just on 18 and more android sdk . so we can't use it.
  shared_preferences: ^2.2.0
  # connectivity_plus: ^4.0.2 #this work just on 19 and more android sdk . so we can't use it.
  cupertino_icons: ^1.0.2
  internet_connection_checker: ^1.0.0+1 

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0
  build_runner: ^2.4.6

  
  flutter_lints: ^2.0.0




flutter:

  
  uses-material-design: true

 
  assets:
    - assets/images/
  

 

  
  fonts:
    - family: shabnamlight
      fonts:
        - asset: assets/fonts/shm.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
    - family: shabnambold
      fonts:
        - asset: assets/fonts/shb.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
