name: store_app_clean_architecture
description: A new Flutter project.
publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  smooth_page_indicator: ^1.1.0
  equatable: ^2.0.5
  dio: ^5.3.0
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  dartz: ^0.10.1
  get_it: ^7.6.0
  cached_network_image: ^3.2.3
  loading_animation_widget: ^1.2.0+4
  dotted_dashed_line: ^0.0.3


  
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^2.0.0




flutter:

  
  uses-material-design: true

 
  assets:
    - assets/images/
  

 

  
  fonts:
    - family: shabnamlight
      fonts:
        - asset: assets/fonts/shm.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
    - family: shabnambold
      fonts:
        - asset: assets/fonts/shb.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
